config/routes.rb
Rails.application.routes.draw do
  resources :dettes do
    get 'set_amount', on: :member
    patch 'update_amount', on: :member
  end
  resources :comptes do
    get 'set_amount', on: :member
    patch 'update_amount', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "comptes#index"
end

app/models/compte.rb
# == Schema Information
#
# Table name: comptes
#
#  id         :bigint           not null, primary key
#  amount     :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Compte < ApplicationRecord
  #================================== Extends ======================================================================
  #================================== Constants ====================================================================
  #================================== Enums ========================================================================
  #================================== Associations =================================================================
  #================================== Scopes =======================================================================
  #================================== Nested Attributes ============================================================
  #================================== Validations ==================================================================
  #================================== Callbacks ====================================================================
  #================================== Methods ======================================================================

  def set_amount(value,set_type)
    self.amount += value  if set_type == "add"
    self.amount -= value  if set_type == "remove"
    self.save
  end
end

app/controllers/comptes_controller.rb
class ComptesController < ApplicationController
  before_action :set_compte, only: %i[ show edit update destroy set_amount update_amount ]

  # GET /comptes or /comptes.json
  def index
    @comptes = Compte.all
    if params[:search].present?
      @comptes = @comptes.where("LOWER(name) ILIKE :search ",
                                      search: "%#{params[:search][:criteria].downcase}%")
    end
  end

  # GET /comptes/1 or /comptes/1.json
  def show
  end

  # GET /comptes/new
  def new
    @compte = Compte.new
  end

  # GET /comptes/1/edit
  def edit
  end
  def set_amount

  end
  def update_amount
    @compte = Compte.find(params[:id])
    transaction_type = params[:compte][:transaction_type]
    transaction_amount = params[:compte][:transaction_amount].to_i
    @compte.set_amount(transaction_amount,transaction_type)
      redirect_to comptes_path, notice: 'Amount updated successfully.'
  end
  # POST /comptes or /comptes.json
  def create
    @compte = Compte.new(compte_params)

    respond_to do |format|
      if @compte.save
        format.html { redirect_to comptes_path, notice: "Compte was successfully created." }
        format.json { render :show, status: :created, location: @compte }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @compte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comptes/1 or /comptes/1.json
  def update
    respond_to do |format|
      if @compte.update(compte_params)
        format.html { redirect_to comptes_path, notice: "Compte was successfully updated." }
        format.json { render :show, status: :ok, location: @compte }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @compte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comptes/1 or /comptes/1.json
  def destroy
    @compte.destroy!

    respond_to do |format|
      format.html { redirect_to comptes_path, notice: "Compte was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compte
      @compte = Compte.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def compte_params
      params.require(:compte).permit(:name, :amount)
    end
end

app/helpers/comptes_helper.rb
module ComptesHelper
end

app/views/comptes/_compte.html.erb
<li id="<%= dom_id compte %>" class="overflow-hidden rounded-xl border border-gray-200">
  <div class="flex items-center gap-x-4 border-b border-gray-900/5 bg-gray-50 p-6">
    <img src="https://tailwindui.com/img/logos/48x48/savvycal.svg" alt="SavvyCal" class="h-12 w-12 flex-none rounded-lg bg-white object-cover ring-1 ring-gray-900/10">
    <div class="text-sm font-medium leading-6 text-gray-900"><%=compte.name %></div>
    <div class="relative ml-auto">
      <button onclick="toggle('<%= compte.id %>')" type="button" class="-m-2.5 block p-2.5 text-gray-400 hover:text-gray-500" id="options-menu-1-button" aria-expanded="false" aria-haspopup="true">
        <span  class="sr-only">Open options</span>
        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M3 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM8.5 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM15.5 8.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" />
        </svg>
      </button>

      <div class="absolute right-0 z-10 mt-0.5 w-32 origin-top-right opacity-0 rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5 focus:outline-none" id="<%= compte.id %>"  role="menu" aria-orientation="vertical" aria-labelledby="options-menu-1-button" tabindex="-1">
        <!-- Active: "bg-gray-50", Not Active: "" -->
        <%= link_to edit_compte_path(compte), class:"block px-3 py-1 text-sm leading-6 text-gray-900" do%>Edit<span class="sr-only">, SavvyCal</span><% end %>
        <%= link_to set_amount_compte_path(compte), class:"block px-3 py-1 text-sm leading-6 text-gray-900" do%>Set<span class="sr-only">, SavvyCal</span><% end %>
        <%= link_to compte_path(compte), class:"block px-3 py-1 text-sm leading-6 text-red-600",  data: {confirm: "are_you_sure", "turbo-method": :delete} do%>delete<span class="sr-only">, SavvyCal</span><% end %>
      </div>
    </div>
  </div>
  <dl class="-my-3 divide-y divide-gray-100 px-6 py-4 text-sm leading-6">
    <div class="flex justify-between gap-x-4 py-3">
      <dt class="text-gray-500">Last update</dt>
      <dd class="text-gray-700"><time datetime="2023-01-22"><%= compte.updated_at || compte.creaated_at %></time></dd>
    </div>
    <div class="flex justify-between gap-x-4 py-3">
      <dt class="text-gray-500">Amount</dt>
      <dd class="flex items-start gap-x-2">
        <div class="font-medium text-gray-900"><%=compte.amount %></div>
        <div class="rounded-md py-1 px-2 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">Paid</div>
      </dd>
    </div>
  </dl>
</li>

app/views/comptes/_form.html.erb
<%= simple_form_for compte, html: {class: "contents"} do |f| %>
  <div class="h-0 flex-1">
    <div class="overflow-x-auto overflow-y-auto h-full pt-2">
      <div class="grid grid-cols-12 gap-x-4 gap-y-6">
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="col-span-full">
          <%= f.input :name, required: true, label_html: {class: "block text-sm font-medium leading-6 text-gray-900 mb-2"}, input_html: {class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"} %>
        </div>
        <div class="col-span-full">
          <%= f.input :amount, required: true, label_html: {class: "block text-sm font-medium leading-6 text-gray-900 mb-2"}, input_html: {class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"} %>
        </div>
      </div>
    </div>
  </div>
  <div class="flex-shrink-0 justify-end mb-6 mt-6">
    <%= f.button :submit, class: "flex w-full justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
  </div>

<% end %>

app/views/comptes/edit.html.erb
<div class="flex h-full flex-col bg-white px-6">
  <div class="flex-none z-0 py-6">
    <%= link_to :back, class: "flex w-full" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18"/>
      </svg>
      <div>
        <p>Account</p>
        <p class="text-sm">edit</p>
      </div>
    <% end %>
  </div>
  <%= render "form", compte: @compte %>
</div>

app/views/comptes/index.html.erb
<div class="flex justify-center my-3">
  <%= link_to new_compte_path, class: "sm:ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 border-transparent bg-indigo-600 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:ring-indigo-500" do %>
    <svg class="-ml-1 mr-2 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
    </svg>
    <span>
            new account
          </span>
  <% end %>
</div>
<ul role="list" class="grid grid-cols-1 gap-x-6 gap-y-8 lg:grid-cols-3 xl:gap-x-8">
<% @comptes.each do |compte| %>
  <%= render  compte %>
  <% end %>

</ul>
<script>
    function toggle(compteID) {
        var menu=document.getElementById(compteID);
        if (menu.classList.contains("opacity-0")) {
            menu.classList.remove("opacity-0")
        } else {
            menu.classList.add("opacity-0")
        }
    }
    function open_menu(){
        var mobile_menu=document.getElementById("mobile-menu");
        if (mobile_menu.classList.contains("hidden")) {
            mobile_menu.classList.remove("hidden")
        } else {
            mobile_menu.classList.add("hidden")
        }
    }
</script>

app/views/comptes/new.html.erb
<div class="flex h-full flex-col bg-white px-6">
  <div class="flex-none z-0 py-6">
    <%= link_to :back, class: "flex w-full" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18"/>
      </svg>
      <div>
        <p>Account</p>
        <p class="text-sm">new</p>
      </div>
    <% end %>
  </div>
  <%= render "form", compte: @compte %>
</div>

app/views/comptes/set_amount.html.erb
<div class="flex h-full flex-col bg-white px-6">
  <div class="flex-none z-0 py-6">
    <%= link_to :back, class: "flex w-full" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18"/>
      </svg>
      <div>
        <p><%= @compte.name %></p>
        <p class="text-sm">edit</p>
      </div>
    <% end %>
  </div>
  <%= form_with(model: @compte, url: update_amount_compte_path(@compte), method: :patch, class: 'contents') do |form| %>
    <div class="h-0 flex-1">
      <div class="overflow-x-auto overflow-y-auto h-full pt-2">
        <div class="grid grid-cols-12 gap-x-4 gap-y-6">
          <div class="col-span-full">
            <%= form.label :transaction_type, class: 'block text-sm font-medium leading-6 text-gray-900 mb-2' %>
            <%= form.select :transaction_type, [['Add', 'add'], ['Remove', 'remove']], { class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', required: true, selected: 'add' } %> </div>

          <div class="col-span-full">
            <%= form.label :transaction_amount, class: 'block text-sm font-medium leading-6 text-gray-900 mb-2' %>
            <%= form.number_field :transaction_amount, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6', required: true %>
          </div>
        </div>
      </div>
    </div>
    <div class="flex-shrink-0 justify-end mb-6 mt-6">
      <%= form.submit 'Submit', class: 'flex w-full justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2' %>
    </div>
  <% end %>
   </div>
</div>

app/views/comptes/show.html.erb
p style="color: green" = notice

== render @compte

div
  => link_to "Edit this compte", edit_compte_path(@compte)
  '|
  =< link_to "Back to comptes", comptes_path

  = button_to "Destroy this compte", @compte, method: :delete